name: running_mate
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  fl_chart: ^0.68.0

  flutter_naver_map: ^1.2.2
  intl: ^0.17.0
  flutter_blue_plus: ^1.32.7
  get: ^4.6.6
  modal_progress_hud_nsn: ^0.5.1
  #fl_chart: ^0.35.0
  cloud_firestore: ^4.17.3
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  cupertino_icons: ^1.0.6
  rive: ^0.13.5
  flutter_slidable: ^3.1.0
  fluttertoast: ^8.2.5
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  provider: ^6.1.2
  table_calendar: ^3.0.8
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: PretendardBold
      fonts:
        - asset: assets/fonts/Pretendard-Bold.ttf
    - family: PretendardSemiBold
      fonts:
        - asset: assets/fonts/Pretendard-SemiBold.ttf
    - family: PretendardRegular
      fonts:
        - asset: assets/fonts/Pretendard-Regular.ttf
    - family: PretendardExBold
      fonts:
        - asset: assets/fonts/Pretendard-ExtraBold.ttf
    - family: PretendardMedium
      fonts:
        - asset: assets/fonts/Pretendard-Medium.ttf

  assets:
    - assets/images/
    - assets/rives/
